// Cada topic es un tramo: la puerta solo pregunta lo que el cartel de antes ya dijo.
// correct tiene que ser idéntico a una opción.

export const STORIES = [
  {
    id: 'hello-semi',
    topic: 'hello',
    kicker: 'El cartel de la escalera',
    q: '¿Qué hace el punto y coma al final de una instrucción?',
    options: ['La cierra', 'La borra', 'La repite', 'La comenta'],
    correct: 'La cierra',
    explain: 'En JavaScript, Java y C el punto y coma cierra la instrucción.',
  },
  {
    id: 'hello-cut',
    topic: 'hello',
    kicker: 'El bicho del suelo',
    q: 'Si el punto y coma corta la frase, ¿qué pasa con el salto?',
    options: ['No llega arriba', 'Se vuelve doble', 'Se queda quieto', 'Atraviesa el suelo'],
    correct: 'No llega arriba',
    explain: 'El cartel lo dice: si la frase se corta, el salto no llega.',
  },
  {
    id: 'hello-print',
    topic: 'hello',
    kicker: 'Hello, world',
    q: '¿Qué muestra print("hola")?',
    options: ['hola', 'print', 'Nada', 'Un error siempre'],
    correct: 'hola',
    explain: 'print muestra el texto que va entre comillas.',
  },
  {
    id: 'hello-where',
    topic: 'hello',
    kicker: 'Dónde va',
    q: '¿Dónde se escribe el punto y coma?',
    options: [
      'Al final de la instrucción',
      'Solo dentro de un comentario',
      'Antes del nombre del archivo',
      'En lugar de las comillas',
    ],
    correct: 'Al final de la instrucción',
    explain: 'Cierra lo que acabas de escribir, como el punto de una frase.',
  },
  {
    id: 'stack-what',
    topic: 'stack',
    kicker: 'El cartel de la pila',
    q: 'En la pila de llamadas, ¿dónde espera cada función?',
    options: [
      'Encima de la anterior',
      'En un archivo aparte',
      'Dentro de un comentario',
      'Debajo del suelo',
    ],
    correct: 'Encima de la anterior',
    explain: 'Cada llamada se apoya en la de abajo y espera su turno.',
  },
  {
    id: 'stack-full',
    topic: 'stack',
    kicker: 'Cuando no caben',
    q: 'Si las llamadas no caben en la pila, ¿qué pasa?',
    options: [
      'Todo pesa: es un desborde',
      'El programa se vuelve más rápido',
      'Se borra el teclado',
      'Las llamadas se hacen comentarios',
    ],
    correct: 'Todo pesa: es un desborde',
    explain: 'Stack overflow: no queda sitio y el salto, aquí, pesa.',
  },
  {
    id: 'stack-self',
    topic: 'stack',
    kicker: 'Llamarse sin parar',
    q: 'Una función que se llama a sí misma sin parar...',
    options: [
      'Llena la pila',
      'Cierra el archivo',
      'Imprime hola una vez',
      'Borra la pila',
    ],
    correct: 'Llena la pila',
    explain: 'Cada llamada nueva se apila. Si no termina, no caben más.',
  },
  {
    id: 'stack-return',
    topic: 'stack',
    kicker: 'Bajar un piso',
    q: '¿Qué hace return dentro de una función?',
    options: [
      'Devuelve un valor y sale',
      'Apila otra llamada',
      'Borra el programa',
      'Dibuja un piso',
    ],
    correct: 'Devuelve un valor y sale',
    explain: 'return termina esa llamada y quita su piso de la pila.',
  },
  {
    id: 'frames-order',
    topic: 'frames',
    kicker: 'Dos porteros',
    q: 'Si A llama a B, ¿quién termina primero?',
    options: ['B, y después A', 'A, y después B', 'Las dos a la vez', 'Ninguna'],
    correct: 'B, y después A',
    explain: 'Termina primero quien fue llamado. Luego sigue el de abajo.',
  },
  {
    id: 'frames-lifo',
    topic: 'frames',
    kicker: 'El orden de la pila',
    q: 'En una pila, ¿qué sale primero?',
    options: [
      'Lo último que entró',
      'Lo primero que entró',
      'El más grande',
      'Un valor al azar',
    ],
    correct: 'Lo último que entró',
    explain: 'Lo de encima sale antes. Por eso B termina antes que A.',
  },
  {
    id: 'frames-braces',
    topic: 'frames',
    kicker: 'El cuerpo',
    q: 'En JavaScript, Java y C, ¿qué agrupa el cuerpo de una función?',
    options: ['{ }', '< >', '# #', '@ @'],
    correct: '{ }',
    explain: 'Las llaves encierran las instrucciones de esa llamada.',
  },
  {
    id: 'frames-fn',
    topic: 'frames',
    kicker: 'Qué es',
    q: '¿Qué es una función?',
    options: [
      'Un bloque de código reutilizable',
      'Un error de la pila',
      'Un comentario',
      'El punto y coma',
    ],
    correct: 'Un bloque de código reutilizable',
    explain: 'La escribes una vez y cada llamada apila un piso nuevo.',
  },
  {
    id: 'enigma-quien',
    tag: 'enigma',
    topic: 'enigma',
    kicker: 'El primer cartel',
    q: '¿Quién inventó la máquina Enigma?',
    options: ['Arthur Scherbius', 'Alan Turing', 'Terry A. Davis', 'Joan Clarke'],
    correct: 'Arthur Scherbius',
    explain: 'Scherbius era ingeniero. La patentó en 1918.',
  },
  {
    id: 'enigma-nombre',
    tag: 'enigma',
    topic: 'enigma',
    kicker: 'El nombre',
    q: '¿Qué significa la palabra enigma?',
    options: ['Acertijo', 'Guerra', 'Torre', 'Lámpara'],
    correct: 'Acertijo',
    explain: 'El cartel lo dice: Enigma quiere decir acertijo.',
  },
  {
    id: 'enigma-rotors',
    tag: 'enigma',
    topic: 'enigma',
    kicker: 'Tres ruedas',
    q: '¿Cuántas ruedas giratorias usaba a la vez la Enigma más común?',
    options: ['3', '26', '1', '16'],
    correct: '3',
    explain: 'Tres ruedas. Giran con cada letra.',
  },
  {
    id: 'enigma-self',
    tag: 'enigma',
    topic: 'enigma',
    kicker: 'El fallo',
    q: 'En la Enigma, ¿una letra podía salir cifrada como ella misma?',
    options: ['No', 'Sí', 'Solo la A', 'Solo de noche'],
    correct: 'No',
    explain: 'Una letra nunca sale igual. Eso ayudó a descifrarla.',
  },
  {
    id: 'enigma-lamp',
    tag: 'enigma',
    topic: 'enigma',
    kicker: 'La lámpara',
    q: 'Al pulsar una tecla en la Enigma, ¿qué se encendía?',
    options: ['Otra letra', 'La misma letra', 'Un número', 'La pantalla del templo'],
    correct: 'Otra letra',
    explain: 'Pulsas una tecla y se enciende otra letra.',
  },
  {
    id: 'turing-cinta',
    tag: 'turing',
    topic: 'turing',
    kicker: '1936',
    q: '¿Qué imaginó Turing en 1936 para explicar qué se puede calcular?',
    options: [
      'Una cinta infinita y una cabeza',
      'Tres ruedas que giran',
      'Una pantalla de 16 colores',
      'Un teléfono',
    ],
    correct: 'Una cinta infinita y una cabeza',
    explain: 'La cabeza lee un símbolo, escribe otro y se mueve.',
  },
  {
    id: 'turing-place',
    tag: 'turing',
    topic: 'turing',
    kicker: 'La guerra',
    q: '¿Dónde trabajó Turing descifrando mensajes?',
    options: ['Bletchley Park', 'Polonia', 'El templo', 'Una torre'],
    correct: 'Bletchley Park',
    explain: 'Joan Clarke trabajó con él ahí, leyendo los mensajes de los barcos.',
  },
  {
    id: 'turing-rejewski',
    tag: 'turing',
    topic: 'turing',
    kicker: 'Antes de la guerra',
    q: '¿Quién, en Polonia, reconstruyó la Enigma antes de la guerra?',
    options: ['Marian Rejewski', 'Arthur Scherbius', 'Terry A. Davis', 'Joan Clarke'],
    correct: 'Marian Rejewski',
    explain: 'Rejewski la reconstruyó en Polonia, antes de Bletchley Park.',
  },
  {
    id: 'turing-bombe',
    tag: 'turing',
    topic: 'turing',
    kicker: 'Esta puerta',
    q: '¿Cómo se llamó la máquina británica que buscaba la clave?',
    options: ['Bombe', 'Enigma', 'HolyC', 'Píxel'],
    correct: 'Bombe',
    explain: 'La Bombe probaba claves. Esta puerta es la suya.',
  },
  {
    id: 'turing-clarke',
    tag: 'turing',
    topic: 'turing',
    kicker: 'El equipo',
    q: '¿Quién leía con Turing los mensajes de los barcos?',
    options: ['Joan Clarke', 'Terry A. Davis', 'Arthur Scherbius', 'Marian Rejewski'],
    correct: 'Joan Clarke',
    explain: 'Clarke era criptoanalista en Bletchley Park, en el equipo de Turing.',
  },
  {
    id: 'temple-quien',
    tag: 'temple',
    topic: 'temple',
    kicker: 'La pirámide',
    q: '¿Quién escribió TempleOS?',
    options: ['Terry A. Davis', 'Alan Turing', 'Arthur Scherbius', 'Joan Clarke'],
    correct: 'Terry A. Davis',
    explain: 'El cartel lo dice: lo escribió él solo.',
  },
  {
    id: 'temple-solo',
    tag: 'temple',
    topic: 'temple',
    kicker: 'Sin equipo',
    q: '¿TempleOS lo hizo un equipo grande?',
    options: ['No, una sola persona', 'Sí, cien personas', 'Solo Turing', 'Nadie sabe'],
    correct: 'No, una sola persona',
    explain: 'Davis programó el sistema, el lenguaje y las herramientas.',
  },
  {
    id: 'temple-lang',
    tag: 'temple',
    topic: 'temple',
    kicker: 'El lenguaje',
    q: '¿Cómo se llama el lenguaje de TempleOS?',
    options: ['HolyC', 'Enigma', 'Bombe', 'Python'],
    correct: 'HolyC',
    explain: 'HolyC es el lenguaje del templo.',
  },
  {
    id: 'temple-c',
    tag: 'temple',
    topic: 'temple',
    kicker: 'Pariente',
    q: '¿A qué lenguaje se parece HolyC?',
    options: ['A C', 'A una cinta de papel', 'A la Enigma', 'A HTML'],
    correct: 'A C',
    explain: 'Es un pariente de C. Se escribe y el templo lo entiende al momento.',
  },
  {
    id: 'temple-res',
    tag: 'temple',
    topic: 'screen',
    kicker: 'La pantalla',
    q: '¿A qué tamaño corre TempleOS?',
    options: ['640 × 480', '1920 × 1080', 'Una pantalla gigante', 'Solo texto'],
    correct: '640 × 480',
    explain: 'La pantalla es pequeña, a propósito.',
  },
  {
    id: 'temple-colors',
    tag: 'temple',
    topic: 'screen',
    kicker: 'Pocos, a propósito',
    q: '¿Cuántos colores muestra TempleOS?',
    options: ['16', '256', '2', 'Millones'],
    correct: '16',
    explain: 'Solo 16 colores. El cartel está bajo el segundo techo.',
  },
  {
    id: 'temple-net',
    tag: 'temple',
    topic: 'screen',
    kicker: 'Sin red',
    q: '¿TempleOS se conectaba a internet?',
    options: ['No', 'Sí, con Wi-Fi', 'Solo de noche', 'Solo para ver videos'],
    correct: 'No',
    explain: 'No se conecta a internet. Era para programar en la misma máquina.',
  },
  {
    id: 'temple-oracle',
    tag: 'temple',
    topic: 'screen',
    kicker: 'El oráculo',
    q: 'El oráculo respondía al azar. ¿Qué juego nombró?',
    options: ['Donkey Kong', 'Tetris', 'Pong', 'Ajedrez'],
    correct: 'Donkey Kong',
    explain: 'El cartel lo dice: el oráculo dijo Donkey Kong.',
  },
  {
    id: 'boss-null',
    topic: 'boss',
    kicker: 'El cartel de la sala',
    q: '¿Qué significa null?',
    options: ['Ausencia de valor', 'El número 0', 'Un texto vacío', 'Verdadero'],
    correct: 'Ausencia de valor',
    explain: 'Null dice que ahí no hay nada. No es lo mismo que 0.',
  },
  {
    id: 'boss-zero',
    topic: 'boss',
    kicker: 'No es un número',
    q: '¿null es lo mismo que 0?',
    options: ['No', 'Sí', 'Solo en la Enigma', 'Solo si es texto'],
    correct: 'No',
    explain: '0 es un número. Null es ausencia de valor.',
  },
  {
    id: 'boss-fault',
    topic: 'boss',
    kicker: 'Segfault',
    q: '¿Cómo se llama cuando usar null mal tira el programa?',
    options: ['Segfault', 'Un comentario', 'Un acertijo', 'HolyC'],
    correct: 'Segfault',
    explain: 'Segfault: el programa tocó algo que no existía y se cae.',
  },
  {
    id: 'boss-crash',
    topic: 'boss',
    kicker: 'Usarlo mal',
    q: '¿Qué pasa al usar null como si hubiera un objeto?',
    options: [
      'El programa se cae',
      'Imprime hola',
      'Abre internet',
      'Suma 1',
    ],
    correct: 'El programa se cae',
    explain: 'No es 0. Usarlo mal tira el programa.',
  },
];
